theme: jekyll-theme-cayman
title: Albert Patera 
description: WWW developer, android apps & programmer

github:
  is_project_page: false
  zip_url: 

owner:
  name: Albert Patera
  avatar: bio-photo.jpg
  bio: "Everything is posible...."
  email: albert.patera@gmail.com